### ISSUE TITLE
how to preprare diy dataset

### ISSUE THREAD

**Issue by wlz987** [yakhyo/face-parsing#1]

**Comment by yakhyo** [comment]
@wlz987 ,

Preparing the dataset is simple. 
1. Download the dataset from:
    - Google drive: [Link to dataset](https://drive.google.com/file/d/1badu11NqxGf6qM3PTTooQDJvQbejgbTv/view)
    - Baidu drive: [Link to dataset](https://pan.baidu.com/s/1wN1E-B1bJ7mE1mrn9loj5g)
  
2.  Unzip the dataset and modify [this file](https://github.com/yakhyo/face-parsing/blob/main/utils/prepare_labels.py) and set the directories for the dataset and masks.
```
face_sep_mask = './Datasets/CelebAMask-HQ-mask-anno'  # specify the path
mask_path = './Datasets/CelebAMask-HQ/mask'  # specify the path to save result masks
```
3. Run the file:
```
python prepare_labels.py
```
