### ISSUE TITLE
What are the labels for categories?

### ISSUE THREAD

**Issue by Elijah-Yi** [yakhyo/face-parsing#3]
thanks for your great work， What are the labels for categories?

**Comment by yakhyo** [comment]
Hi @Elijah-Yi ,


It's available in data preparation file, [here](https://github.com/yakhyo/face-parsing/blob/main/utils/prepare_labels.py#L11C1-L30C2):

```
attributes = [
    'skin',
    'l_brow',
    'r_brow',
    'l_eye',
    'r_eye',
    'eye_g',
    'l_ear',
    'r_ear',
    'ear_r',
    'nose',
    'mouth',
    'u_lip',
    'l_lip',
    'neck',
    'neck_l',
    'cloth',
    'hair',
    'hat'
]
```
Above is all available classes for categories, however when you train the model there will be index 0 for background.
so class map should have `background` class at index 0:

```
classes = [
    'background',
    'skin',
    'l_brow',
    'r_brow',
    'l_eye',
    'r_eye',
    'eye_g',
    'l_ear',
    'r_ear',
    'ear_r',
    'nose',
    'mouth',
    'u_lip',
    'l_lip',
    'neck',
    'neck_l',
    'cloth',
    'hair',
    'hat'
]
```

**Comment by yakhyo** [comment]
ref: 
https://github.com/yakhyo/face-parsing/blob/main/utils/common.py#L5
https://github.com/yakhyo/face-parsing/blob/main/utils/common.py#L26
https://github.com/yakhyo/face-parsing/blob/main/utils/prepare_labels.py#L11C1-L30C2

**Comment by Elijah-Yi** [comment]
thanks
